#! /bin/sh

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d '' '' '' '' '' '' '' '' '󰊖'

bspc config border_width 2
bspc config window_gap 9
bspc config focus_follows_pointer true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#8aadf4"
bspc config normal_border_color "#363a4f"
bspc config active_border_color "#62AEEF"
bspc config presel_feedback_color "#8aadf4"

# Fix padding
bspc config bottom_padding 0
bspc config top_padding 0

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans
killall -9 xsettingsd lxpolkit sxhkd picom polybar plank xfce4-clipman
# remove all rules first
bspc rule -r *:*a

#Where to pop up
## 1 > apps to Workspace 1
bspc rule -a Alacritty desktop='^1' follow=on focus=on


## 2 > apps to Workspace 2
declare -a browsers=(Brave-browser firefox)
for i in ${browsers[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

## 3 > apps to Workspace 3
declare -a code=(Code geany nvim)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

## 4 > apps to Workspace 4
#declare -a fm=(Thunar)
#for i in ${fm[@]}; do
#   bspc rule -a $i desktop='^4' follow=on focus=on; done

bspc rule -a Thunar desktop='^4' follow=on focus=on

## 5 > apps to Workspace 5
#declare -a office=(Thunderbird)
#for i in ${office[@]}; do
#   bspc rule -a $i desktop='^5' follow=on focus=on; done

bspc rule -a Thunderbird desktop='^5' follow=on focus=on
bspc rule -a "ONLYOFFICE Desktop Editors" desktop='^5' follow=on focus=on

## 6 > apps to Workspace 6
declare -a comms=(WhatSie TelegramDesktop)
for i in ${comms[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

## 7 > apps to Workspace 7
declare -a media=(Gimp-2.10 vlc com.github.neithern.g4music)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

## 8 > apps to Workspace 8
declare -a conf=(Lxappearance obs)
for i in ${conf[@]}; do
   bspc rule -a $i desktop='^8' follow=on focus=on; done

## 8 > apps to Workspace 9
declare -a games=("Minecraft* 1.20.1" java unityhub)
for i in ${games[@]}; do
   bspc rule -a $i desktop='^9' follow=on focus=on; done
 
## Always Floating Apps
declare -a floating=(alacritty-float WhatSie kitty java com.github.neithern.g4music Geany Thunderbird xdman-Main firefox:places TelegramDesktop Thunar Viewnior Nm-connection-editor "net-fabricmc-loader-impl-launch-knot-KnotClient")
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

#Plank always top
bash ~/.config/bspwm/plank.sh &

#================Autostart================#

xsettingsd &
lxpolkit &
sxhkd &
~/.fehbg
# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
picom &
polybar &
plank &
xfce4-clipman &

# Fix cursor
xsetroot -cursor_name left_ptr
