bind=Super, R, exec, /usr/bin/morghulis -q && /usr/bin/uwsm app -- morghulis
bindr=Super, D, exec, /usr/bin/morghulis -t Runner
bindr=Super, X, exec, /usr/bin/morghulis -t PowerMenu
bindr=Super, S, exec, /usr/bin/morghulis -t ScreenRecord
bindr=Super, I, exec, /usr/bin/morghulis -i

layerrule {
  name = morghulis-navbar
  match:namespace = Morghulis.NavBar
  animation = slide
}

layerrule {
  name = morghulis-quickmenu
  match:namespace = Morghulis.QuickMenu
  animation = slide right
}

layerrule {
  name = morghulis-osd
  match:namespace = Morghulis.OnScreenDisplay
  animation = slide
}

layerrule {
  name = morghulis-notifications
  match:namespace = Morghulis.Notifications
  no_anim = on
}

layerrule {
  name = morghulis-powermenu
  match:namespace = Morghulis.PowerMenu
  animation = slide
}

layerrule {
  name = morghulis-runner
  match:namespace = Morghulis.Runner
  animation = popin 50%
}

layerrule {
  name = morghulis-screenrecord
  match:namespace = Morghulis.ScreenRecord
  no_anim = on
}
