bind=Super, R, exec, /usr/bin/morghulctl -q && /usr/bin/uwsm app -- morghulis
bindr=Super, D, exec, /usr/bin/morghulctl -t Runner
bindr=Super, X, exec, /usr/bin/morghulctl -t PowerMenu
bindr=Super, I, exec, /usr/bin/morghulctl -i
