bind=Super, R, exec, /usr/bin/morghulis -q && /usr/bin/uwsm app -- morghulis
bindr=Super, D, exec, /usr/bin/morghulis -t Runner
bindr=Super, X, exec, /usr/bin/morghulis -t PowerMenu
bindr=Super, I, exec, /usr/bin/morghulis -i

layerrule = animation slide, Morghulis.NavBar
layerrule = animation slide right, Morghulis.QuickMenu
layerrule = animation slide, Morghulis.OnScreenDisplay
layerrule = animation slide, Morghulis.PowerMenu
layerrule = animation popin 50%, Morghulis.Runner
