#!/bin/env bash

commands=(
	"$HOME/.dotfiles/scripts/wbg"
	"/usr/bin/dbus-update-activation-environment --all"
	"/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh"
	"/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
)

# Iterate over the commands and start them
for cmd in "${commands[@]}"; do
	$cmd &
done
