# Brave
#--------2
windowrule = workspace 2, class:^(.*[Bb]rave-browser.*)$
# ----Brave_PIP
windowrule = float,title:(Picture in picture)
windowrule = size 600 350,title:(Picture in picture)
windowrule = move 1310 720,title:(Picture in picture)
windowrule = pin,title:(Picture in picture)
#----Brave_Save_File
windowrule = float,class:(brave),title:(Save File)
windowrule = size 715 570,class:(brave),title:(Save File)
windowrule = move 710 160,class:(brave),title:(Save File)

# Code and Zed
#--------3
windowrule = workspace 3, class:^(code.*)$
windowrule = workspace 3, class:^(dev.zed.Zed)$

#--------4
windowrule = workspace 4, class:^(.*[Nn]autilus.*)$
# Thunar
windowrule = workspace 4, class:^(.*[Tt]hunar.*)$
windowrule= size 400 150,class:([Tt]hunar),title:(Create New Folder)
windowrule= move 485 350,class:([Tt]hunar),title:(Create New Folder)
windowrule = float,class:(Player),title:(Player)

#--------5
windowrule = workspace 5, class:^([Dd]iscord)$
windowrule = workspace 5, class:^(org.telegram.desktop)$

#--------6
windowrule = workspace 6, class:^([Ll]ibreoffice.*)$

#--------7
windowrule = workspace 7, title:^(.*[Ss]ound[Cc]loud.*)$

#--------8
windowrule = workspace 8, class:^(.*uget-gtk.*)$
windowrule = workspace 8, class:^(.*bleachbit.*)$

# Waydroid and Steam
#--------9
windowrule = workspace 9,class:^(.*[Ss]team.*)$
windowrule = workspace 9,class:^(faugus-.*)$

#--------10

# Floatcritty
windowrule=float,class:^(floatcritty)$
windowrule=size 900 600,class:^(floatcritty)$
windowrule=move 510 50,class:^(floatcritty)$
windowrule=pin,class:^(floatcritty)$
windowrule=animation slide,class:^(floatcritty)$

# Engrampa
windowrule=float,class:^(engrampa)$

# Kitty
windowrule=noblur,class:^(kitty)$
windowrule=float,class:^(kitty)
windowrule=size 900 520,class:^(kitty)
windowrule=move 230 160,class:^(kitty)

# ProtonVPN
windowrule = pin, class:^(protonvpn-app)
windowrule = size 400 600, class:^(protonvpn-app)
windowrule = move 10 420, class:^(protonvpn-app)

#---WhatsApp
windowrule = workspace 5, title:^(.*WhatsApp.*)$
windowrule = tile, title:^(.*WhatsApp.*)$


# NoBlur
windowrule = noblur, class:^(vlc)$
windowrule = noblur, class:^(.*[Bb]rave-browser.*)$
